print('asdjhjd')
from core import pinBot
a=pinBot()
#a.followBoard('philippawestlee/must-have')
#print(a.getFollowingBoards())
#print(a.getFollowingUsers())
ids,users = a.search('pooop','board',2)
print(users)
print("*****")
print(ids)
